version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.java
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"